[tool.poetry]
name = "icon-service-base"
version = "0.1.0"
description = "Repository storing the code that is common to all icon services."
authors = ["Mose Mueller <mosmuell@ethz.ch>"]
license = "MIT"
readme = "README.md"
packages = [{include = "icon_service_base"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
